name: CI/CD
on: push
jobs:
  lint-build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun run check
      - run: bun run build
      - name: Install deps for functions
        working-directory: functions
        run: bun install
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v13.4.0
        with:
          args: deploy
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_DYVOXYZ }}
